spring.application.name=movierating

omdb.api.key=4db2273

jwt.secret=813f8bcd0af80d927c688a0a7e807c5a813f8bcd0af80d927c688a0a7e807c5a
jwt.expiration=3600000

spring.data.mongodb.uri=mongodb://localhost:27017/movieratingdb